### ISSUE TITLE
No require check when using table constructor

### ISSUE THREAD

**Issue by jbreuer95** [kurapica/PLoop#11]
Using latest version in Wow Classic

Example class:
```
PLoop(function(_ENV)
    class "Announcement" (function(_ENV)
        property "title" { Require = true, Type = String }
        property "created" { Require = true, Type = String }
        property "author" { Require = true, Type = String }
        property "body" { Require = true, Type = String }
    end)
end)
```
// OK
`test = Announcement{ title = 'title', created = 'created', author = 'author', body = 'body'  }`

// OK (Error: title must be string )
`test = Announcement{ title = 1, created = 'created', author = 'author', body = 'body'  }`

// OK (Error: title cannot be nil)
```
test = Announcement{ title = 'title', created = 'created', author = 'author', body = 'body'  }
test.title = nil
```
// Problem (no error thrown)
`test = Announcement{ title = nil, created = 'created', author = 'author', body = 'body'  }`

Am i doing something wrong?

**Comment by kurapica** [comment]
{ title = nil } equals to the { },  the init-table for class constructor is works like 

``` lua
test = Announcement()

for k, v in pairs{ title = nil, created = 'created } do
    -- the title won't be set to the test object, so the error won't occur
    test[k] = v
end
```

This init-table usage is only works for class with no constructor, so you shouldn't use it as a validator.

The class is not really used for that, what you need is the struct type 

``` lua
PLoop(function(_ENV)
    struct "Announcement" (function(_ENV)
        member "title" { Require = true, Type = String }
        member "created" { Require = true, Type = String }
        member "author" { Require = true, Type = String }
        member "body" { Require = true, Type = String }
    end)

    -- Error:  Usage: Announcement(title, created, author, body) - the title can't be nil
    test = Announcement{ title = nil, created = 'created', author = 'author', body = 'body' }
end)
```

If  you don't need method for those objects, the struct type will meet your requirement. If you really need it to be a class, you should do like this:

``` lua
PLoop(function(_ENV)
    struct "AnnouncementType" (function(_ENV)
        member "title" { Require = true, Type = String }
        member "created" { Require = true, Type = String }
        member "author" { Require = true, Type = String }
        member "body" { Require = true, Type = String }
    end)

    class "Announcement" (function(_ENV)
        property "title" { Require = true, Type = String }
        property "created" { Require = true, Type = String }
        property "author" { Require = true, Type = String }
        property "body" { Require = true, Type = String }

        __Arguments__{ AnnouncementType }
        function __ctor(self, init)
        	for k, v in pairs(init) do
        		self[k] = v
        	end
        end
    end)

    --  Usage: Announcement(AnnouncementType) - the 1st argument.title can't be n
    o = Announcement{ title = nil, created = 'created', author = 'author', body = 'body' }
end)
```

The `__Arguments__` will make sure the Announcement use the AnnouncementType as the parameter for the constructor. So the AnnouncementType will do the validation for the Announcement.

In PLoop, almost all value validation are done by the structs.

**Comment by jbreuer95** [comment]
Thank you for the very detailed explantion!

PS. I am really loving PLoop and Scorpio is is very powerfull

**Comment by kurapica** [comment]
The PLoop & Scorpio's retail version can be used in the classic, just need change their toc number. I have only lvl 12 charater in classic, so the update frequency of the classic version is lower, only update with big changes.

If you have other problems of the usage, you can contact me with discord: kurapica#2104
