### ISSUE TITLE
A sudden flash of a console

### ISSUE THREAD

**Issue by CodeMasterYi** [kurapica/PLoop#4]
I can see a sudden flash of a Console when I launch my Unity3d project with "require('PLoop.init')" under a Framework called xLua~
I can not figure out what causes this~

**Comment by kurapica** [comment]
I'm not familiar with xLua, it seems the default loader only load files with '.txt' suffix in the Resources folder.

You may try to append the '.txt' suffix for all Lua files in the PLoop, or add a custom loader for 3rd-party Lua  module, or change the package.path so PLoop can be found.

**Comment by CodeMasterYi** [comment]
Ehhh...You are right.
Well, what I say is that I have succeeded Integrating `PLoop` into my project on Windows, but when i click Lauch on Unity Editor & execute require('PLoop.init'), it lauches a console and then disapears.
So, i guess there is some api launch it ~ i doubt
Certainly, i am sure that if i do not import PLoop, it does not happen.

**Comment by kurapica** [comment]
Well, I think it's the PLoop.System.IO lib, you can disable it in the PLoop.init, change the

`if type(io) == "table" then`

to

`if false then`

It has no use for the Unity3d

**Comment by CodeMasterYi** [comment]
yeah, you make it~lots of thanks!
