### ISSUE TITLE
documentation is missing

### ISSUE THREAD

**Issue by winterskill** [kurapica/PLoop#6]
Today, I have wanted to view the online documentation, and I seen that it is missing. Only the home page exists, and click on a link redirect to the home page...

**Comment by kurapica** [comment]
Those documents are used for the old PLoop, you can find the current version of them all in the **readme**. 

The wiki will be used to save the documents for classes and other features.  But for now, all system features are introduced in the Readme(except the System.Date which you can find it in the wiki), the others will be added when I finished the PLoop_Web & PLoop_Nginx.
