### ISSUE TITLE
does PLoop support lua 5.3 or 5.4?

### ISSUE THREAD

**Issue by ForeverDreamer** [kurapica/PLoop#7]
Just be sure , thank you!

**Comment by ForeverDreamer** [comment]
Why am I not able to do Breakpoint Debugging in eclipse LDT?

**Comment by kurapica** [comment]
Yes, it'd works well in Lua 5.3 and 5.4.

The LDT is just too slow to debug a lib like PLoop, try other IDE or just use Log do the job.
